### ISSUE TITLE
Materialize does not preserve the device/dtype information

### ISSUE THREAD

**Issue by YangFei1990** [pytorch/torchdistx#11]
**Describe the bug:**
`Materialize` will always create the tensor on CPU, regardless of the fake tensor device

**Describe how to reproduce:**
```
import torch
from torchdistx.deferred_init import deferred_init, materialize_module
m = deferred_init(torch.nn.Linear, 2, 2)
print(m.weight.device) # cpu
m.cuda()
print(m.weight.device) # cuda:0
materialize_module(m)
print(m.weight.device) # still cpu
```

**Describe the expected behavior:**
Materialize should initialize the tensor to the right device

**Environment:**
- OS: Ubuntu 18.04
- PT Version: 1.11.0+cu113
- torchdistx is installed by `pip install torchdistx --extra-index-url https://download.pytorch.org/whl/cu113`

**Additional context:**

**Comment by YangFei1990** [comment]
It also happens for `dtype` in certain cases.
This will be buggy:
```
import torch
from torchdistx.deferred_init import materialize_tensor, deferred_init
m = deferred_init(torch.nn.Linear, 2, 2)
m.half()
print(m.weight.dtype) # float16
m.weight = materialize_tensor(m.weight)
print(m.weight.dtype) # float32
```
But if the tensor is created with the right dtype, it is fine:
```
import torch
from torchdistx.deferred_init import materialize_tensor, deferred_init
torch.set_default_dtype(torch.float16)
m = deferred_init(torch.nn.Linear, 2, 2)
torch.set_default_dtype(torch.float32)
print(m.weight.dtype) # float16
m.weight = materialize_tensor(m.weight)
print(m.weight.dtype) # float16
```

**Comment by cbalioglu** [comment]
Hi @YangFei1990, this is by design. Any operation (e.g. `half()`) should be part of your module initialization function. We only trace operators that happen inside `deferred_init()`. So your example can be written like the following to make it compatible with our behavior:

```
import torch
from torchdistx.deferred_init import materialize_tensor, deferred_init

def LinearHalf(*args, **kwargs):
  lin = torch.nn.Linear(*args, **kwargs)
  return lin.half()

m = deferred_init(LinearHalf, 2, 2)
print(m.weight.dtype) # float16
m.weight = materialize_tensor(m.weight)
print(m.weight.dtype) # float16
```

**Comment by YangFei1990** [comment]
If this is by design, can you add documentation for that? It is very easy for pytorch users to make such mistakes and it is not easy to debug.

**Comment by cbalioglu** [comment]
Sure! Just reopened the issue. I will have a PR next week.
