### ISSUE TITLE
torchdistx's support to PT1.12

### ISSUE THREAD

**Issue by yongyanrao** [pytorch/torchdistx#28]
Does torchdistx support PT1.12, and what is the currency policy? Raising the issue since the installation of torchdistx causes uninstalling PT1.12 and installing PT1.11.

**Comment by rohan-varma** [comment]
It looks like PyTorch 1.12 just released: https://github.com/pytorch/pytorch/releases/tag/v1.12.0, so we should be able to officially bump the torchdistx version now.

**Comment by cbalioglu** [comment]
@yongyanrao we just released torchdistx v0.2.0 that supports PyTorch 1.12.

**Comment by yongyanrao** [comment]
Thank you so much. It really helps.
