### ISSUE TITLE
Optimizers dir doesn't have __init__.py

### ISSUE THREAD

**Issue by atturaioe** [pytorch/torchdistx#63]
**Describe the bug:**
Cannot import `AnyPrecisionAdamW` since the `optimizers` dir doesn't have `__init__.py` and is not treated as a python module

**Comment by rohan-varma** [comment]
@atturaioe 

Thanks for filing the issue! As discussed in your fix PR this issue has since been resolved. Please feel free to leave any feedback on trying out `AnyPrecisionOptimizer`, we'd love to understand your use case as well!
